# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-12 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.CharField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
