# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 15:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0004_jobapplication_cover_letter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employer',
            new_name='Company',
        ),
        migrations.RenameModel(
            old_name='JobSeeker',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='cover_letter',
            field=models.CharField(max_length=200),
        ),
    ]
