# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-14 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0007_auto_20170314_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='join_date',
        ),
    ]
