# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal', '0009_auto_20170315_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(default='one off', max_length=200),
            preserve_default=False,
        ),
    ]
