# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-12 04:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name=b'Name')),
                ('var_name', models.SlugField(max_length=32, unique=True, verbose_name=b'Slug')),
                ('title', models.TextField(blank=True, verbose_name=b'Title')),
                ('description', models.TextField(blank=True, verbose_name=b'Description')),
                ('keywords', models.TextField(blank=True, verbose_name=b'Keywords')),
                ('category_order', models.PositiveIntegerField(blank=True, unique=True, verbose_name=b'Category order')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name=b'Name')),
                ('ascii_name', models.SlugField(unique=True, verbose_name=b'ASCII Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name=b'Title')),
                ('description', models.TextField(verbose_name=b'Description')),
                ('description_html', models.TextField(editable=False)),
                ('company', models.CharField(max_length=150, verbose_name=b'Company')),
                ('company_slug', models.SlugField(editable=False, max_length=150)),
                ('outside_location', models.CharField(blank=True, max_length=150, verbose_name=b'Outside location')),
                ('url', models.URLField(blank=True, max_length=150)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2017, 3, 11, 22, 2, 4, 930095), editable=False, verbose_name=b'Created on')),
                ('status', models.IntegerField(choices=[(0, b'Inactive'), (1, b'Temporary'), (2, b'Active')], default=1)),
                ('views_count', models.IntegerField(default=0, editable=False)),
                ('auth', models.CharField(blank=True, editable=False, max_length=32)),
                ('joburl', models.CharField(blank=True, editable=False, max_length=32)),
                ('poster_email', models.EmailField(help_text=b'Applications will be sent to this address.', max_length=254, verbose_name=b'Poster email')),
                ('apply_online', models.BooleanField(default=True, help_text=b'If you are unchecking this, then add a description on how to apply online!', verbose_name=b'Allow online applications.')),
                ('spotlight', models.BooleanField(default=False, verbose_name=b'Spotlight')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djobberbase.Category', verbose_name=b'Category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djobberbase.City', verbose_name=b'City')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='JobSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=100, verbose_name=b'Keywords')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2017, 3, 11, 22, 2, 4, 932203), verbose_name=b'Created on')),
            ],
            options={
                'verbose_name': 'Search',
                'verbose_name_plural': 'Searches',
            },
        ),
        migrations.CreateModel(
            name='JobStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2017, 3, 11, 22, 2, 4, 931496))),
                ('ip', models.GenericIPAddressField()),
                ('stat_type', models.CharField(choices=[(b'A', b'Application'), (b'H', b'Hit'), (b'S', b'Spam')], max_length=1)),
                ('description', models.CharField(max_length=250, verbose_name=b'Description')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djobberbase.Job')),
            ],
            options={
                'verbose_name': 'Job Stat',
                'verbose_name_plural': 'Job Stats',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True, verbose_name=b'Name')),
                ('var_name', models.SlugField(max_length=32, unique=True, verbose_name=b'Slug')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='jobtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djobberbase.Type', verbose_name=b'Job Type'),
        ),
    ]
